[tool.poetry]
name = "checks"
version = "0.1.0"
description = "Sekoia Automate Modules check"
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
python-dateutil = "^2.8.2"
pillow = "^10.3.0"
jsonschema = "^4.22.0"
numpy = "^1.26.4"
pydantic = "^2.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
