[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "Automation module for Netskope"
version = "0.0"
description = ""
authors = []
package-mode = false

[tool.black]
line-length = 119
target-version = [ "py314",]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
line_length = 119

[tool.mypy]
exclude = [ "tests/*", "dev.py",]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
netskopesdk = "^0.0.34"
google-cloud-pubsublite = "^1.8.3"
google-api-python-client = "^2.95.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^1.0.0"
google-api-core = "^2.11.1"
google-auth = "^2.22.0"
googleapis-common-protos = "^1.59.1"
structlog = "^24.4.0"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
requests = "*"
requests-mock = "*"
autoflake = "^1.4"
isort = "^5.10.1"

[tool.coverage.run]
omit = [ "tests/*", "dev.py", "main.py",]

[tool.poetry.dependencies.sekoia-automation-sdk]
version = "^1.21.2"
extras = [ "all",]

[tool.poetry.dev-dependencies.black]
version = "^24.3.0"
extras = [ "colorama",]

[tool.poe.tasks.lint]
help = "Make code linting and formatting."
[[tool.poe.tasks.lint.sequence]]
cmd = "poetry run autoflake --in-place --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variables */**/*.py"

[[tool.poe.tasks.lint.sequence]]
cmd = "poetry run black ."

[[tool.poe.tasks.lint.sequence]]
cmd = "poetry run isort ."

